Extension { #name : #BlElementLocalBounds }

{ #category : #'*Carlone' }
BlElementLocalBounds >> bottomLeft [
	^ self asRectangle bottomLeft
]

{ #category : #'*Carlone' }
BlElementLocalBounds >> bottomRight [
	^ self asRectangle bottomRight
]

{ #category : #'*Carlone' }
BlElementLocalBounds >> topLeft [
	^ self asRectangle topLeft
]

{ #category : #'*Carlone' }
BlElementLocalBounds >> topRight [
	^ self asRectangle topRight
]
